from django.contrib.auth.views import (
    LoginView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path, reverse_lazy
from .views import (
    PublicHomeView,
    PublicPlansView,
    PublicContactView,
    OficinaSignupView,
    SubscriptionBlockedView,
    SubscriptionCancelView,
    SubscriptionDetailView,
    AssinaturaPaymentCreateView,
    AsaasConnectionTestView,
    AsaasPixTestChargeView,
    AsaasWebhookView,
    BookingCreateView,
    AppHomeView,
    MinhaOficinaView,
    PublicBookingCreateView,
    BookingSuccessView,
    PublicBookingSuccessView,
    DashboardView,
    BoxesPanelView,
    BookingStatusUpdateView,
    DeleteBookingView,
    AvailableSlotsView,
    OrdemServicoListView,
    OrdemServicoDetailView,
    OrdemServicoServiceItemCreateView,
    OrdemServicoServiceItemDeleteView,
    OrdemServicoPartItemCreateView,
    OrdemServicoPartItemDeleteView,
    OrdemServicoPartItemUpdateView,
    OrdemServicoPartSearchView,
    OrdemServicoFinancialUpdateView,
    OrdemServicoCreateFromBookingView,
    OrdemServicoStatusUpdateView,
    OrdemServicoPrintView,
    ExportBookingsExcelView,
    FinanceDashboardView,
    FinanceExportExcelView,
    FinanceExportPdfView,
    FinanceInvoiceView,
    logout_view,
    EstoqueOverviewView,
    EstoqueListView,
    EstoqueItemCreateView,
    EstoqueItemUpdateView,
    EstoqueMovementCreateView,
    EstoqueMovementsView,
    EstoqueLowView,
)

app_name = 'agenda'

urlpatterns = [
    path('', PublicHomeView.as_view(), name='home'),
    path('planos/', PublicPlansView.as_view(), name='plans'),
    path('contato/', PublicContactView.as_view(), name='contact'),
    path('cadastro/', OficinaSignupView.as_view(), name='signup'),
    path('assinatura/', SubscriptionDetailView.as_view(), name='subscription_detail'),
    path('assinatura/bloqueada/', SubscriptionBlockedView.as_view(), name='subscription_blocked'),
    path('assinatura/cancelar/', SubscriptionCancelView.as_view(), name='subscription_cancel'),
    path('assinatura/pagar/', AssinaturaPaymentCreateView.as_view(), name='subscription_pay'),
    path('financeiro/asaas/teste/', AsaasConnectionTestView.as_view(), name='asaas_connection_test'),
    path('financeiro/asaas/pix-teste/', AsaasPixTestChargeView.as_view(), name='asaas_pix_test_charge'),
    path('webhooks/asaas/', AsaasWebhookView.as_view(), name='asaas_webhook'),
    path('agendar/', BookingCreateView.as_view(), name='booking'),
    path('oficina/<slug:slug>/agendar/', PublicBookingCreateView.as_view(), name='public_booking'),
    path('oficina/<slug:slug>/agendar/sucesso/', PublicBookingSuccessView.as_view(), name='public_booking_success'),
    path('agendar/success/', BookingSuccessView.as_view(), name='booking_success'),
    path('agendar/available-slots/', AvailableSlotsView.as_view(), name='available_slots'),
    path('login/', LoginView.as_view(template_name='registration/login.html', redirect_authenticated_user=True), name='login'),
    path(
        'senha/recuperar/',
        PasswordResetView.as_view(
            template_name='registration/password_reset_form.html',
            email_template_name='agenda/registration/password_reset_email.html',
            html_email_template_name='agenda/registration/password_reset_email.html',
            subject_template_name='registration/password_reset_subject.txt',
            success_url=reverse_lazy('agenda:password_reset_done'),
        ),
        name='password_reset',
    ),
    path(
        'senha/recuperar/enviado/',
        PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        'senha/nova/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
            success_url=reverse_lazy('agenda:password_reset_complete'),
        ),
        name='password_reset_confirm',
    ),
    path(
        'senha/nova/concluido/',
        PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete',
    ),
    path('logout/', logout_view, name='logout'),
    path('app/', AppHomeView.as_view(), name='app_home'),
    path('minha-oficina/', MinhaOficinaView.as_view(), name='minha_oficina'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('agenda/boxes/', BoxesPanelView.as_view(), name='boxes_panel'),
    path('dashboard/export-excel/', ExportBookingsExcelView.as_view(), name='export_bookings_excel'),
    path('financeiro/', FinanceDashboardView.as_view(), name='finance_dashboard'),
    path('financeiro/export-excel/', FinanceExportExcelView.as_view(), name='finance_export_excel'),
    path('financeiro/export-pdf/<int:pk>/', FinanceExportPdfView.as_view(), name='finance_export_pdf'),
    path('financeiro/invoice/<int:pk>/', FinanceInvoiceView.as_view(), name='finance_invoice'),
    path('dashboard/update-status/', BookingStatusUpdateView.as_view(), name='update_status'),
    path('dashboard/delete/', DeleteBookingView.as_view(), name='delete_booking'),
    path('os/', OrdemServicoListView.as_view(), name='os_list'),
    path('os/create/<int:booking_id>/', OrdemServicoCreateFromBookingView.as_view(), name='create_os'),
    path('os/<int:pk>/', OrdemServicoDetailView.as_view(), name='os_detail'),
    path('os/<int:pk>/service/add/', OrdemServicoServiceItemCreateView.as_view(), name='os_service_add'),
    path('os/<int:pk>/service/<int:item_pk>/delete/', OrdemServicoServiceItemDeleteView.as_view(), name='os_service_delete'),
    path('os/<int:pk>/part/add/', OrdemServicoPartItemCreateView.as_view(), name='os_part_add'),
    path('os/<int:pk>/part/search/', OrdemServicoPartSearchView.as_view(), name='os_part_search'),
    path('os/<int:pk>/part/<int:item_pk>/update/', OrdemServicoPartItemUpdateView.as_view(), name='os_part_update'),
    path('os/<int:pk>/part/<int:item_pk>/delete/', OrdemServicoPartItemDeleteView.as_view(), name='os_part_delete'),
    path('os/<int:pk>/financial/', OrdemServicoFinancialUpdateView.as_view(), name='os_financial_update'),
    path('os/<int:pk>/update-status/', OrdemServicoStatusUpdateView.as_view(), name='update_os_status'),
    path('os/<int:pk>/print/', OrdemServicoPrintView.as_view(), name='os_print'),
    path('estoque/', EstoqueOverviewView.as_view(), name='stock_overview'),
    path('estoque/pecas/', EstoqueListView.as_view(), name='stock_list'),
    path('estoque/pecas/nova/', EstoqueItemCreateView.as_view(), name='stock_create'),
    path('estoque/pecas/<int:pk>/editar/', EstoqueItemUpdateView.as_view(), name='stock_update'),
    path('estoque/pecas/<int:pk>/movimentar/', EstoqueMovementCreateView.as_view(), name='stock_move'),
    path('estoque/movimentacoes/', EstoqueMovementsView.as_view(), name='stock_movements'),
    path('estoque/baixo/', EstoqueLowView.as_view(), name='stock_low'),
]
