# Generated by Django 6.0.5 on 2026-06-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nome completo')),
                ('phone', models.CharField(max_length=25, verbose_name='Telefone')),
                ('vehicle_brand', models.CharField(max_length=80, verbose_name='Marca do veículo')),
                ('vehicle_model', models.CharField(max_length=80, verbose_name='Modelo do veículo')),
                ('vehicle_year', models.PositiveSmallIntegerField(verbose_name='Ano do veículo')),
                ('problem_description', models.TextField(verbose_name='Problema informado')),
                ('service_type', models.CharField(choices=[('oil', 'Troca de óleo'), ('alignment', 'Alinhamento'), ('balancing', 'Balanceamento'), ('basic_review', 'Revisão básica'), ('complete_review', 'Revisão completa'), ('electronic_diagnosis', 'Diagnóstico eletrônico'), ('custom', 'Serviço personalizado')], max_length=20, verbose_name='Tipo de serviço')),
                ('custom_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Informe o tempo em minutos apenas para serviço personalizado.', null=True, verbose_name='Tempo personalizado (minutos)')),
                ('duration_minutes', models.PositiveIntegerField(editable=False, verbose_name='Tempo estimado (minutos)')),
                ('scheduled_date', models.DateField(verbose_name='Data do agendamento')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('in_progress', 'Em andamento'), ('completed', 'Finalizado'), ('canceled', 'Cancelado')], default='scheduled', max_length=20, verbose_name='Status do serviço')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-scheduled_date', 'status', 'full_name'],
            },
        ),
    ]
