# Generated by Django 6.0.5 on 2026-06-01 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['scheduled_date', 'start_time', 'full_name'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='custom_duration_minutes',
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Horário de início'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 minutos'), (60, '1 hora'), (90, '1 hora e 30 minutos'), (120, '2 horas'), (150, '2 horas e 30 minutos'), (180, '3 horas'), (210, '3 horas e 30 minutos'), (240, '4 horas'), (270, '4 horas e 30 minutos'), (300, '5 horas'), (330, '5 horas e 30 minutos'), (360, '6 horas'), (390, '6 horas e 30 minutos'), (420, '7 horas'), (450, '7 horas e 30 minutos'), (480, '8 horas')], verbose_name='Tempo estimado (minutos)'),
        ),
    ]
