# Generated by Django 6.0.5 on 2026-06-01 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_booking_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=15, unique=True, verbose_name='Número da OS')),
                ('client_name', models.CharField(max_length=120, verbose_name='Nome do cliente')),
                ('phone', models.CharField(max_length=25, verbose_name='Telefone')),
                ('vehicle_brand', models.CharField(max_length=80, verbose_name='Marca do veículo')),
                ('vehicle_model', models.CharField(max_length=80, verbose_name='Modelo do veículo')),
                ('vehicle_year', models.PositiveSmallIntegerField(verbose_name='Ano do veículo')),
                ('plate', models.CharField(blank=True, max_length=20, verbose_name='Placa')),
                ('problem_description', models.TextField(verbose_name='Problema relatado')),
                ('duration_minutes', models.PositiveSmallIntegerField(choices=[(30, '30 minutos'), (60, '1 hora'), (90, '1 hora e 30 minutos'), (120, '2 horas'), (150, '2 horas e 30 minutos'), (180, '3 horas'), (210, '3 horas e 30 minutos'), (240, '4 horas'), (270, '4 horas e 30 minutos'), (300, '5 horas'), (330, '5 horas e 30 minutos'), (360, '6 horas'), (390, '6 horas e 30 minutos'), (420, '7 horas'), (450, '7 horas e 30 minutos'), (480, '8 horas')], verbose_name='Tempo estimado (minutos)')),
                ('scheduled_date', models.DateField(verbose_name='Data do agendamento')),
                ('observations', models.TextField(blank=True, verbose_name='Observações da oficina')),
                ('status', models.CharField(choices=[('received', 'Recebido'), ('analysis', 'Em análise'), ('waiting_approval', 'Aguardando aprovação'), ('in_execution', 'Em execução'), ('completed', 'Finalizado'), ('delivered', 'Entregue'), ('canceled', 'Cancelado')], default='received', max_length=20, verbose_name='Status da OS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_servico', to='agenda.booking')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Recebido'), ('analysis', 'Em análise'), ('waiting_approval', 'Aguardando aprovação'), ('in_execution', 'Em execução'), ('completed', 'Finalizado'), ('delivered', 'Entregue'), ('canceled', 'Cancelado')], max_length=20, verbose_name='Status')),
                ('note', models.TextField(blank=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='agenda.ordemservico')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de OS',
                'verbose_name_plural': 'Histórico de OS',
                'ordering': ['created_at'],
            },
        ),
    ]
