# Generated by Django 6.0.5 on 2026-06-02 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_ordemservico_ordemservicostatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluído em'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='estimated_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lucro estimado'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='mechanic_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Mecânico responsável'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quilometragem'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='parts_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total de peças'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('transfer', 'Transferência'), ('pix', 'PIX'), ('credit', 'Crédito'), ('debit', 'Débito'), ('other', 'Outro')], max_length=25, verbose_name='Forma de pagamento'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='service_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do serviço'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='warranty',
            field=models.CharField(blank=True, default='30 dias', max_length=120, verbose_name='Garantia do serviço'),
        ),
        migrations.CreateModel(
            name='CashFlowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='Data')),
                ('entry_type', models.CharField(choices=[('inflow', 'Entrada'), ('outflow', 'Saída')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_records', to='agenda.ordemservico')),
            ],
            options={
                'verbose_name': 'Registro de fluxo de caixa',
                'verbose_name_plural': 'Registros de fluxo de caixa',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=180, verbose_name='Ação')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_audit', to='agenda.ordemservico')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria financeira',
                'verbose_name_plural': 'Auditorias financeiras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('receivable', 'A receber'), ('payable', 'A pagar'), ('cash_in', 'Entrada'), ('cash_out', 'Saída')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Vencido')], default='pending', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('transfer', 'Transferência'), ('pix', 'PIX'), ('credit', 'Crédito'), ('debit', 'Débito'), ('other', 'Outro')], max_length=25, verbose_name='Forma de pagamento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='agenda.ordemservico')),
            ],
            options={
                'verbose_name': 'Movimentação financeira',
                'verbose_name_plural': 'Movimentações financeiras',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoPartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=180, verbose_name='Peça')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor unitário')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_items', to='agenda.ordemservico')),
            ],
            options={
                'verbose_name': 'Peça utilizada',
                'verbose_name_plural': 'Peças utilizadas',
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=180, verbose_name='Serviço')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor unitário')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='agenda.ordemservico')),
            ],
            options={
                'verbose_name': 'Serviço executado',
                'verbose_name_plural': 'Serviços executados',
            },
        ),
    ]
