# Generated by Django 6.0.5 on 2026-06-07 16:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_fix_estoque_codigo_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('teste', 'Teste'), ('ativo', 'Ativo'), ('vencido', 'Vencido'), ('bloqueado', 'Bloqueado')], default='teste', max_length=20, verbose_name='Status da assinatura')),
                ('trial_started_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Inicio do teste gratis')),
                ('trial_ends_at', models.DateField(blank=True, null=True, verbose_name='Fim do teste gratis')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vencimento da mensalidade')),
                ('last_payment_at', models.DateField(blank=True, null=True, verbose_name='Data do ultimo pagamento')),
                ('payment_method', models.CharField(blank=True, choices=[('pix', 'Pix'), ('cartao_credito', 'Cartao de credito')], max_length=30, verbose_name='Forma de pagamento')),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=8, verbose_name='Valor mensal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('oficina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='agenda.oficina', verbose_name='Cliente/empresa')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['oficina__nome'],
            },
        ),
    ]
