# Generated by Django 6.0.5 on 2026-06-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='ID do cliente no Asaas'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='asaas_invoice_url',
            field=models.URLField(blank=True, verbose_name='Link de pagamento Asaas'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='asaas_payment_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='ID da cobranca no Asaas'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='asaas_pix_payload',
            field=models.TextField(blank=True, verbose_name='Copia e cola Pix'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='cidade',
            field=models.CharField(blank=True, max_length=80, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='documento',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail comercial'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='endereco',
            field=models.CharField(blank=True, max_length=180, verbose_name='Endereco'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='oficinas/logos/', verbose_name='Logo da oficina'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='telefone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Telefone/WhatsApp'),
        ),
    ]
