# Generated by Django 6.0.5 on 2026-06-08 17:56

from django.db import migrations, models
from django.utils.text import slugify


def populate_oficina_slugs(apps, schema_editor):
    Oficina = apps.get_model('agenda', 'Oficina')
    used_slugs = set(
        Oficina.objects.exclude(slug__isnull=True).exclude(slug='').values_list('slug', flat=True)
    )
    for oficina in Oficina.objects.order_by('id'):
        if oficina.slug:
            continue
        base_slug = slugify(oficina.nome) or f'oficina-{oficina.pk}'
        slug = base_slug
        counter = 2
        while slug in used_slugs:
            slug = f'{base_slug}-{counter}'
            counter += 1
        oficina.slug = slug
        oficina.save(update_fields=['slug'])
        used_slugs.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_assinatura_asaas_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Slug publico'),
        ),
        migrations.RunPython(populate_oficina_slugs, migrations.RunPython.noop),
    ]
