# Generated by Django 6.0.5 on 2026-06-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_oficina_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_phone', models.CharField(max_length=20, verbose_name='Telefone destino')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('error', models.TextField(blank=True, verbose_name='Erro')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='agenda.booking', verbose_name='Agendamento')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='agenda.oficina', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
