# Generated by Django 6.0.5 on 2026-06-12 14:35

from decimal import Decimal
from datetime import timedelta

from django.db import migrations, models


def update_existing_subscriptions(apps, schema_editor):
    Assinatura = apps.get_model('agenda', 'Assinatura')
    new_amount = Decimal('99.90')
    old_amount = Decimal('150.00')

    for assinatura in Assinatura.objects.all():
        update_fields = []

        if assinatura.status == 'teste':
            if assinatura.trial_started_at:
                trial_ends_at = assinatura.trial_started_at + timedelta(days=20)
                if assinatura.trial_ends_at != trial_ends_at:
                    assinatura.trial_ends_at = trial_ends_at
                    update_fields.append('trial_ends_at')
                if assinatura.due_date != trial_ends_at:
                    assinatura.due_date = trial_ends_at
                    update_fields.append('due_date')
            if assinatura.monthly_amount != new_amount:
                assinatura.monthly_amount = new_amount
                update_fields.append('monthly_amount')
        elif assinatura.monthly_amount == old_amount:
            assinatura.monthly_amount = new_amount
            update_fields.append('monthly_amount')

        if update_fields:
            assinatura.save(update_fields=sorted(set(update_fields)))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_whatsappmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='monthly_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('99.90'), max_digits=8, verbose_name='Valor mensal'),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='status',
            field=models.CharField(choices=[('teste', 'Teste'), ('ativo', 'Ativo'), ('vencido', 'Vencido'), ('bloqueado', 'Bloqueado'), ('cancelada', 'Cancelada')], default='teste', max_length=20, verbose_name='Status da assinatura'),
        ),
        migrations.RunPython(update_existing_subscriptions, noop_reverse),
    ]
