# Generated by Django 6.0.5 on 2026-06-14 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_update_remaining_subscription_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_box',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Box alocado'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='business_type',
            field=models.CharField(choices=[('car', 'Mecânica de carro'), ('motorcycle', 'Mecânica de moto'), ('electrical', 'Auto elétrica'), ('other', 'Outra')], default='other', max_length=20, verbose_name='Tipo de oficina'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='mechanic_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de boxes'),
        ),
    ]
