# Generated by Django 6.0.5 on 2026-06-14 16:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_booking_assigned_box_oficina_business_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Box')),
                ('start_datetime', models.DateTimeField(verbose_name='Inicio do bloqueio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fim do bloqueio')),
                ('reason', models.CharField(blank=True, max_length=180, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='agenda.oficina', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Bloqueio de Box',
                'verbose_name_plural': 'Bloqueios de Box',
                'ordering': ['start_datetime', 'box_number'],
            },
        ),
    ]
