# Generated by Django 6.0.5 on 2026-06-14 16:32

from django.db import migrations, models


def copy_telefone_to_whatsapp(apps, schema_editor):
    Oficina = apps.get_model('agenda', 'Oficina')
    for oficina in Oficina.objects.filter(whatsapp='').exclude(telefone=''):
        oficina.whatsapp = oficina.telefone
        oficina.save(update_fields=['whatsapp'])


def clear_copied_whatsapp(apps, schema_editor):
    Oficina = apps.get_model('agenda', 'Oficina')
    Oficina.objects.update(whatsapp='')


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_boxblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='cep',
            field=models.CharField(blank=True, max_length=12, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descricao'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=25, verbose_name='WhatsApp'),
        ),
        migrations.RunPython(copy_telefone_to_whatsapp, clear_copied_whatsapp),
    ]
