# Generated by Django 6.0.5 on 2026-07-28 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_oficina_cep_oficina_descricao_oficina_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Saída'), ('adjustment', 'Ajuste'), ('os_usage', 'Uso em Ordem de Serviço'), ('reversal', 'Estorno')], max_length=20, verbose_name='Tipo')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('quantidade_anterior', models.PositiveIntegerField()),
                ('quantidade_posterior', models.PositiveIntegerField()),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='estoqueitem',
            name='unique_codigo_estoque_por_oficina',
        ),
        migrations.AddField(
            model_name='estoqueitem',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='estoqueitem',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=80, verbose_name='Código de barras'),
        ),
        migrations.AddField(
            model_name='estoqueitem',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='estoqueitem',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Estoque mínimo'),
        ),
        migrations.AddField(
            model_name='estoqueitem',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='estoqueitem',
            name='marca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='estoqueitem',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de venda'),
        ),
        migrations.AddField(
            model_name='estoqueitem',
            name='unidade_medida',
            field=models.CharField(default='un', max_length=20, verbose_name='Unidade de medida'),
        ),
        migrations.AddField(
            model_name='ordemservicopartitem',
            name='estoque_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordem_items', to='agenda.estoqueitem', verbose_name='Peça do estoque'),
        ),
        migrations.AddField(
            model_name='ordemservicopartitem',
            name='stock_quantity_applied',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade já baixada'),
        ),
        migrations.AddField(
            model_name='ordemservicopartitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo unitário registrado'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('oil', 'Troca de óleo'), ('personal_analysis', 'Analisar pessoalmente'), ('basic_review', 'Revisão básica'), ('complete_review', 'Revisão completa'), ('electronic_diagnosis', 'Diagnóstico eletrônico'), ('custom', 'Serviço personalizado')], max_length=20, verbose_name='Tipo de serviço'),
        ),
        migrations.AlterField(
            model_name='estoqueitem',
            name='codigo',
            field=models.CharField(max_length=60, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='estoquecategoria',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='agenda.oficina', verbose_name='Oficina'),
        ),
        migrations.AddField(
            model_name='estoqueitem',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='agenda.estoquecategoria'),
        ),
        migrations.AddIndex(
            model_name='estoqueitem',
            index=models.Index(fields=['oficina', 'ativo'], name='agenda_esto_oficina_a29898_idx'),
        ),
        migrations.AddIndex(
            model_name='estoqueitem',
            index=models.Index(fields=['oficina', 'nome'], name='agenda_esto_oficina_9b6f06_idx'),
        ),
        migrations.AddConstraint(
            model_name='estoqueitem',
            constraint=models.UniqueConstraint(fields=('oficina', 'codigo'), name='unique_codigo_estoque_por_oficina'),
        ),
        migrations.AddConstraint(
            model_name='estoqueitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 0)), name='estoque_quantidade_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='estoqueitem',
            constraint=models.CheckConstraint(condition=models.Q(('estoque_minimo__gte', 0)), name='estoque_minimo_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='estoqueitem',
            constraint=models.CheckConstraint(condition=models.Q(('custo_unitario__gte', 0)), name='estoque_custo_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='estoqueitem',
            constraint=models.CheckConstraint(condition=models.Q(('preco_venda__gte', 0)), name='estoque_venda_nao_negativa'),
        ),
        migrations.AddField(
            model_name='estoquemovimentacao',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='agenda.estoqueitem'),
        ),
        migrations.AddField(
            model_name='estoquemovimentacao',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='agenda.oficina', verbose_name='Oficina'),
        ),
        migrations.AddField(
            model_name='estoquemovimentacao',
            name='ordem_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='agenda.ordemservicopartitem'),
        ),
        migrations.AddField(
            model_name='estoquemovimentacao',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='agenda.ordemservico'),
        ),
        migrations.AddField(
            model_name='estoquemovimentacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='estoquecategoria',
            constraint=models.UniqueConstraint(fields=('oficina', 'nome'), name='unique_categoria_estoque_por_oficina'),
        ),
        migrations.AddIndex(
            model_name='estoquemovimentacao',
            index=models.Index(fields=['oficina', '-created_at'], name='agenda_esto_oficina_d0478f_idx'),
        ),
        migrations.AddIndex(
            model_name='estoquemovimentacao',
            index=models.Index(fields=['oficina', 'tipo'], name='agenda_esto_oficina_f89eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='estoquemovimentacao',
            index=models.Index(fields=['item', '-created_at'], name='agenda_esto_item_id_9638fa_idx'),
        ),
    ]
