# Generated by Django 6.0.5 on 2026-07-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_estoquecategoria_estoquemovimentacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservicopartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Adicionado em'),
        ),
    ]
