# Generated by Django 6.0.5 on 2026-07-28 19:47

import django.db.models.deletion
from django.db import migrations, models


def validate_financial_uniqueness(apps, schema_editor):
    from django.db.models import Count

    FinancialTransaction = apps.get_model('agenda', 'FinancialTransaction')
    CashFlowRecord = apps.get_model('agenda', 'CashFlowRecord')
    duplicate_receivables = FinancialTransaction.objects.exclude(
        ordem_servico_id=None
    ).filter(transaction_type='receivable').values(
        'ordem_servico_id'
    ).annotate(total=Count('id')).filter(total__gt=1)
    duplicate_inflows = CashFlowRecord.objects.exclude(
        ordem_servico_id=None
    ).filter(entry_type='inflow', status='active').values(
        'ordem_servico_id'
    ).annotate(total=Count('id')).filter(total__gt=1)
    if duplicate_receivables.exists() or duplicate_inflows.exists():
        raise RuntimeError(
            'Existem lançamentos financeiros duplicados por OS. '
            'Revise-os antes de aplicar a migration 0018; nenhum dado foi removido.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_ordemservicopartitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowrecord',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='agenda.cashflowrecord', verbose_name='Estorno de'),
        ),
        migrations.AddField(
            model_name='cashflowrecord',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('reversed', 'Estornado')], default='active', max_length=12, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Vencido'), ('canceled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.RunPython(validate_financial_uniqueness, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='cashflowrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'inflow'), ('ordem_servico__isnull', False), ('status', 'active')), fields=('ordem_servico',), name='unique_active_inflow_por_os'),
        ),
        migrations.AddConstraint(
            model_name='financialtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('ordem_servico__isnull', False), ('transaction_type', 'receivable')), fields=('ordem_servico',), name='unique_receivable_por_os'),
        ),
    ]
