# Generated by Django 6.0.5 on 2026-07-28 19:51

from django.db import migrations, models


def validate_order_items(apps, schema_editor):
    PartItem = apps.get_model('agenda', 'OrdemServicoPartItem')
    ServiceItem = apps.get_model('agenda', 'OrdemServicoServiceItem')
    invalid_parts = PartItem.objects.filter(
        models.Q(quantity__lte=0)
        | models.Q(unit_price__lt=0)
        | models.Q(unit_cost__lt=0)
    )
    invalid_services = ServiceItem.objects.filter(
        models.Q(quantity__lte=0) | models.Q(unit_price__lt=0)
    )
    if invalid_parts.exists() or invalid_services.exists():
        raise RuntimeError(
            'Existem itens de OS com quantidade/preço/custo inválido. '
            'Revise-os antes da migration 0019; nenhum dado foi alterado.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0018_cashflowrecord_reversal_of_cashflowrecord_status_and_more'),
    ]

    operations = [
        migrations.RunPython(validate_order_items, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='ordemservicopartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='os_part_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='ordemservicopartitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='os_part_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='ordemservicopartitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='os_part_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='ordemservicoserviceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='os_service_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='ordemservicoserviceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='os_service_price_nonnegative'),
        ),
    ]
