# Generated by Django 6.0.5 on 2026-07-28 20:08

import django.db.models.deletion
from django.db import migrations, models


def backfill_current_asaas_payments(apps, schema_editor):
    Assinatura = apps.get_model('agenda', 'Assinatura')
    AsaasPayment = apps.get_model('agenda', 'AsaasPayment')
    for assinatura in Assinatura.objects.exclude(asaas_payment_id='').iterator():
        if not assinatura.asaas_customer_id:
            continue
        AsaasPayment.objects.create(
            oficina_id=assinatura.oficina_id,
            assinatura_id=assinatura.pk,
            payment_id=assinatura.asaas_payment_id,
            customer_id=assinatura.asaas_customer_id,
            external_reference=f'assinatura-{assinatura.pk}',
            billing_type='CREDIT_CARD' if assinatura.payment_method == 'cartao_credito' else 'PIX',
            amount=assinatura.monthly_amount,
            status='received' if assinatura.last_payment_at else 'pending',
            invoice_url=assinatura.asaas_invoice_url,
            paid_at=assinatura.last_payment_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_ordemservicopartitem_os_part_quantity_positive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsaasWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('payment_id', models.CharField(blank=True, max_length=80)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processando'), ('processed', 'Processado'), ('ignored', 'Ignorado'), ('failed', 'Falhou')], default='processing', max_length=20)),
                ('detail', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_id', 'event_type'], name='agenda_asaa_payment_08aba8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AsaasPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=80, unique=True, verbose_name='ID da cobranca no Asaas')),
                ('customer_id', models.CharField(max_length=80, verbose_name='ID do cliente no Asaas')),
                ('external_reference', models.CharField(max_length=120)),
                ('billing_type', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('received', 'Recebido'), ('canceled', 'Cancelado'), ('refunded', 'Estornado')], default='pending', max_length=20)),
                ('invoice_url', models.URLField(blank=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asaas_payments', to='agenda.assinatura')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='agenda.oficina', verbose_name='Oficina')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['oficina', 'assinatura', 'status'], name='agenda_asaa_oficina_f8ac51_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='asaas_payment_amount_positive')],
            },
        ),
        migrations.RunPython(backfill_current_asaas_payments, migrations.RunPython.noop),
    ]
