# Generated by Django 6.0.5 on 2026-07-28 20:23

from django.db import migrations, models


def initialize_order_number_sequence(apps, schema_editor):
    OrdemServico = apps.get_model('agenda', 'OrdemServico')
    OrderNumberSequence = apps.get_model('agenda', 'OrderNumberSequence')
    current_value = 0
    for order_number in OrdemServico.objects.values_list('order_number', flat=True).iterator():
        if order_number and order_number.startswith('OS-'):
            try:
                current_value = max(current_value, int(order_number[3:]))
            except ValueError:
                continue
    OrderNumberSequence.objects.update_or_create(
        pk=1,
        defaults={'current_value': current_value},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0020_asaaswebhookevent_asaaspayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.RunPython(initialize_order_number_sequence, migrations.RunPython.noop),
    ]
